config/routes.rb
Rails.application.routes.draw do
  namespace :host do
    resources :listings
   
  end
  get 'static_pages/home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: 'static_pages#home'
  devise_for :users
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/listing.rb
# == Schema Information
#
# Table name: listings
#
#  id            :bigint           not null, primary key
#  host_id       :bigint           not null
#  title         :string           not null
#  about         :text
#  max_guests    :integer          default(1)
#  address_line1 :string
#  address_line2 :string
#  city          :string
#  state         :string
#  postal_code   :string
#  country       :string
#  lat           :decimal(10, 6)
#  lng           :decimal(10, 6)
#  status        :integer          default(0)
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#
class Listing < ApplicationRecord
  validates :title, presence: true
  validates :max_guests, numericality: { greater_than: 0 , less_than_or_equal_to: 100 }
  belongs_to :host, class_name: "User"
  enum status: [:draft, :published, :archived]
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  confirmation_token     :string
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string
#  failed_attempts        :integer          default(0), not null
#  unlock_token           :string
#  locked_at              :datetime
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :lockable, :timeoutable, :trackable


  has_many :listings, foreign_key: :host_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/host/listings_controller.rb
class Host::ListingsController < ApplicationController
  def new
    @listing = Listing.new
  end

  def create 
    @listing = current_user.listings.new(listing_create_params)
   if @listing.save
    redirect_to @listing
   else 
    flash.now[:errors] = @listing.errors.full_messages
    render :new
   end
  end

  def edit
    @listing = currrnt_user.listings.find(params[:id])
  end

  def update 
@listing = current_user.listings.find(params[:id])
if @listing.update(listing_update_params)
  redirect_to @listing
else 
  flash.now[:errors] = @listing.errors.full_messages
  render :edit

  end

  def index
    @listings = current_user.listings.all
  end

  def show
    @listing = current_user.listings.find(params[:id])
  end

  def destroy
    @listing = current_user.listings.find(params[:id])
    @listing.update(status:  :archived)
    respond_to host_listings_path


  end

  private 


  def listing_create_params
   params.require(:listing).permit(:title, :about, :max_guests, :address_line1, :address_line2, :city, :state, :postal_code, :country)
  end

  def listing_update_params
    params.require(:listing).permit(:title, :about, :max_guests)
  end
end 
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/host/listings_helper.rb
module Host::ListingsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/host/listings/edit.html.erb
<h1>Host::Listings#edit</h1>
<p>Find me in app/views/host/listings/edit.html.erb</p>

app/views/host/listings/index.html.erb
<h1>Your Listings</h1>


<% @listings.each do |l| %>
    <%= link_to l.title, host_listing_path(l) %>
        <% end %>

app/views/host/listings/new.html.erb
<h1>Host::Listings#new</h1>
<p>Find me in app/views/host/listings/new.html.erb</p>

app/views/host/listings/show.html.erb
<h1>Host::Listings#show</h1>
<p>Find me in app/views/host/listings/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Clearbnb</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

      <%= stylesheet_link_tag "application" , "data-turbo-track": "reload" %>
        <%= javascript_importmap_tags %>
</head>

<body>
  <p class="notice">
    <%= notice %>
  </p>
  <p class="alert">
    <%= alert %>
  </p>
  <%= yield %>
</body>

</html>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>